// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB77PCSVyAxQNmaiw0D56NBgttbIZiekQs',
    appId: '1:617622530809:web:ce336cbcd46813ad099028',
    messagingSenderId: '617622530809',
    projectId: 'fooddelivery-33f84',
    authDomain: 'fooddelivery-33f84.firebaseapp.com',
    storageBucket: 'fooddelivery-33f84.appspot.com',
    measurementId: 'G-77QMEMHP8H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL2rbKzv3-50r3x3DUUWQd05YoRKFFuQI',
    appId: '1:617622530809:android:b3f5b617c1f7d966099028',
    messagingSenderId: '617622530809',
    projectId: 'fooddelivery-33f84',
    storageBucket: 'fooddelivery-33f84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4KDhfKO0P_mixSrasvlBy2nE82n2mwEk',
    appId: '1:617622530809:ios:d792354691d040d7099028',
    messagingSenderId: '617622530809',
    projectId: 'fooddelivery-33f84',
    storageBucket: 'fooddelivery-33f84.appspot.com',
    iosClientId: '617622530809-kq1giffnr5ne5rg5li7ha714hmutraa6.apps.googleusercontent.com',
    iosBundleId: 'com.example.monkeyAppDemo',
  );
}
